baseURL = 'https://reliable-ganache-c5d1bb.netlify.app/'
languageCode = 'en-us'
title = "Samir's Portfolio"
theme = "gallery"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.83.0"

[params]
  # BORRÉ LA LÍNEA 'author = "Samir"' DE AQUÍ PARA EVITAR EL ERROR
  description = "Street Photography & Code"
  mainSections = ["albums"]  # <--- Esto arregla tu portada
  
  # Configuración correcta del autor (objeto)
  [params.author]
    name = "Samir"
    email = "samir.saad@gmail.com"

  # Redes sociales
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/___._samir_.___/"
    
  [[params.social]]
    name = "github"
    url = "https://github.com/AlienWrangler"

[menu]
  [[menu.main]]
    identifier = "albums"
    name = "Galería"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 20